// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(SchedulerContext))]
    partial class SchedulerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "feruchio599@gmail.com",
                            FirstName = "Maverick",
                            Gender = "Male",
                            LastName = "Cloud",
                            PhoneNumber = "088-61-62-835",
                            UpdatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Maverick"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saad@gmail.com",
                            FirstName = "Saad",
                            Gender = "Male",
                            LastName = "Salim",
                            PhoneNumber = "999-888-7777",
                            UpdatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Saad"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "xinoredm@gmail.com",
                            FirstName = "Xinored",
                            Gender = "Male",
                            LastName = "Deronix",
                            PhoneNumber = "939-858-7977",
                            UpdatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Xinored"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "badboy@gmail.com",
                            FirstName = "Badboy",
                            Gender = "Male",
                            LastName = "Boy",
                            PhoneNumber = "989-158-7877",
                            UpdatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Badboy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roller@gmail.com",
                            FirstName = "Roller",
                            Gender = "Male",
                            LastName = "Rolls",
                            PhoneNumber = "039-855-7927",
                            UpdatedAt = new DateTime(2019, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Mr.Roller"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
